#!/bin/bash
set -e

echo "KEYMAP=gb" | sudo tee -a /etc/vconsole.conf
localectl --no-convert set-x11-keymap gb pc104

sudo pacman -Syu --noconfirm - < pkglist

sudo mariadb-install-db --user=mysql --basedir=/usr --datadir=/var/lib/mysql
sudo systemctl enable --now mariadb.service

mkdir -p ~/scripts ~/work ~/dev ~/recordings

cp -a config/. /home/ash/.config/
cp -a scripts/. /home/ash/scripts/
wget https://raw.githubusercontent.com/tremby/imgur.sh/main/imgur.sh -O ~/scripts/imgur
cp -R wallpapers/ /home/ash/wallpapers

sudo chmod +x /home/ash/scripts/*

sudo mkdir /mnt/storage

echo "/dev/disk/by-uuid/eab3b3c5-7473-4308-bf3a-633def59c06c /mnt/storage auto nosuid,nodev,nofail,x-gvfs-show 0 0" | sudo tee -a /etc/fstab
systemctl daemon-reload
sudo mount -a

git clone https://aur.archlinux.org/yay.git && cd yay && makepkg -si
yay -Syu jetbrains-toolbox spotify plex-media-server zsh vlc waybar-git swaylock-effects swww cava-git wlogout google-chrome aria2 docker-desktop --noconfirm

timedatectl set-timezone Europe/London

echo 'deny = 5' | sudo tee -a /etc/security/faillock.conf

cp other/.vimrc /home/ash/.vimrc

sh -c "$(curl -fsSL raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

cp other/.zshrc /home/ash/.zshrc

sudo usermod -a -G vboxusers ash

git config --global user.name "ashdevelops"
git config --global user.email "ash.smith.dev@gmail.com"

sudo systemctl enable --now bluetooth.service
sudo systemctl enable --now plexmediaserver

# cp -R /mnt/storage/ssh-backup ~/.ssh
# sudo chmod -R 600 ~/.ssh/work*  ~/.ssh/personal* 

sudo systemctl enable --now sddm.service

# sudo /usr/bin/mysql_secure_installation
