#!/bin/bash

STATUS_JSON=$(~/Hubstaff/HubstaffCLI.bin.x86_64 status)
IS_TRACKING=$(jq -r .tracking <<< $STATUS_JSON)

if [ 'false' = "$IS_TRACKING" ]; then 
    echo "Timer Stopped"
    exit
fi

PROJECT_NAME=$(jq -r .active_project.name <<< $STATUS_JSON)
TIME_SPENT=$(jq -r .active_project.tracked_today <<< $STATUS_JSON)


echo "$PROJECT_NAME - $TIME_SPENT"
