#!/usr/bin/env bash

if pgrep -x "wf-recorder" > /dev/null
then
    killall -s SIGINT wf-recorder
    FILE=$(ls -t $RECORDPATH | head -n1)
    notify-send "Screen Recording Complete" "Saved to $FILE"
    wl-copy $FILE
	while [ ! -z $(pgrep -x wf-recorder) ]; do wait; done
	pkill -RTMIN+8 waybar
    exit
fi

if ! yad --title='Confirm?' --center --fixed --undecorated --button=Yes:0 --button=No:1 --text="You sure you wanna $1?" --text-align=center --align=center --justify=center --buttons-layout=center; then
    exit
fi

FILENAME=$(date +%F_%T.mkv)

wf-recorder -f $HOME/recordings/$FILENAME format=rgb24 -x rgb24 -p qp=0 -p crf=0 -p preset=veryslow -p tune=animation -c libx264rgb -g "$(slurp -c "#FFFFFF")" >/dev/null 2>&1 &
