#!/bin/bash

IMG=/tmp/$(date +%Y-%m-%d_%H-%m-%s).png 
grim -g "$(slurp)" $IMG 
swappy -f $IMG -o $IMG
echo $IMG
SAVED=$($HOME/scripts/imgur $IMG)
notify-send "Screenshot Saved" $SAVED
wl-copy $SAVED
rm $IMG
