#!/usr/bin/env bash

sleep 0.6

RBG1=$(ls ~/wallpapers | shuf -n 1)
RBG2=$(ls ~/wallpapers | shuf -n 1)

hyprctl hyprpaper wallpaper "HDMI-A-1,~/wallpapers/$RBG1"
hyprctl hyprpaper wallpaper "DP-1,~/wallpapers/$RBG2"
