#!/bin/bash

RANDOM=$(ls ~/wallpapers | shuf -n 1)
RANDOM2=$(ls ~/wallpapers | shuf -n 1)

hyprctl hyprpaper wallpaper "HDMI-1,~/wallpapers/$RANDOM2"
hyprctl hyprpaper wallpaper "DP-1,~/wallpapers/$RANDOM2"
